FROM quay.io/wildfly/wildfly

USER root

# Add the path for the maven binaries
ADD packages/apache-maven-3.9.6 /home/apache-maven-3.9.6
ADD learning /home/learning

RUN /home/apache-maven-3.9.6/bin/mvn clean package -f "/home/learning/pom.xml" \
    && cp /home/learning/target/learning.war /opt/jboss/wildfly/standalone/deployments/ \
    && /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

EXPOSE 8080
EXPOSE 9990

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
